// Generated by app/tools/emit-engine.mjs from engine/facts.gen.json
// (the engine's own `DocConfig::default()`, registry and notices, serialised by
// engine/src/facts.rs) and from the prelude's `#let` lines.
// Do not edit by hand: run `node tools/emit-engine.mjs`.
// `npm test` fails when this file and the engine disagree.
//
// Three facts the engine already knows, which this side used to know separately:
// the document defaults, the Hebrew↔English command pairing, and what the engine
// redistributes. See the generator's header for why each is generated rather
// than fetched.

/**
 * The engine's own document defaults, as `DocConfig::default()` states them.
 *
 * The four per-edge margins and the note region are **absent** rather than
 * zero — absent means "follow the uniform margin" / "decide from the document",
 * which is a different instruction from any number. (margin_top_cm, margin_bottom_cm, margin_inner_cm, margin_outer_cm, page_width_cm, page_height_cm, notes_region_cm)
 */
export const DOC_DEFAULTS = {
  font: "Frank Ruhl Hofshi",
  size_pt: 12,
  margin_cm: 2.5,
  gutter_cm: 0,
  two_sided: false,
  header_even: "",
  header_odd: "",
  footer_even: "",
  footer_odd: "",
  head_align: "center",
  title: "",
  author: "",
  keywords: [],
  pdf_standard: "",
  pdf_tagged: true,
  prevent_orphans: false,
  dir: "rtl",
  numbering: true,
  justify: true,
  text_align: "",
  line_spacing_em: 0.75,
  para_spacing_em: 1.2,
  first_line_indent_em: 0,
  columns: 1,
  paper: "a4",
  hebrew_numbering: false,
  header: "",
  footer: "",
} as const;

/**
 * The English alias of every command, keyed by its Hebrew name.
 *
 * From the prelude's own `#let` lines, which are what *make* the pairing —
 * so this covers the four tiers per family that the palette registry stops
 * short of, and an export meets a document that used one.
 */
export const COMMAND_EN: Readonly<Record<string, string>> = {
  "הגדרות_הערות": "footnote_config",
  "הערה_בדרגה": "tier",
  "מדור_בדרגה": "band",
  "מדור_א": "band1",
  "מדור_ב": "band2",
  "מדור_ג": "band3",
  "מדור_ד": "band4",
  "מדור_ה": "band5",
  "מדור_ו": "band6",
  "מדור_ז": "band7",
  "הערות_מדורגות": "banded_notes",
  "הגדרות_מדורגות": "banded_config",
  "מדף_בדרגה": "pageband",
  "מדף_א": "pageband1",
  "מדף_ב": "pageband2",
  "מדף_ג": "pageband3",
  "מדף_ד": "pageband4",
  "מדף_ה": "pageband5",
  "מדף_ו": "pageband6",
  "מדף_ז": "pageband7",
  "הגדרות_מדפים": "pagebands_config",
  "הערה_זרם": "stream_note",
  "הערת_תוכן": "contentnote",
  "הערת_מקור": "sourcenote_stream",
  "הגדרות_זרמים": "streams_config",
  "ערוץ": "channel",
  "אזור": "region",
  "הצג_אזור": "show_region",
  "הערה_א": "tier1",
  "הערה_ב": "tier2",
  "הערה_ג": "tier3",
  "הערה_ד": "tier4",
  "הערה_ה": "tier5",
  "הערה_ו": "tier6",
  "הערה_ז": "tier7",
  "הגדרות_כותרת1": "h1_config",
  "הגדרות_כותרת2": "h2_config",
  "הגדרות_כותרת3": "h3_config",
  "הגדרות_כותרת4": "h4_config",
  "הגדרות_כותרת5": "h5_config",
  "הגדרות_כותרת6": "h6_config",
  "הגדרות_כותרות": "headings_config",
  "הגדרות_רשימות": "lists_config",
  "הגדרות_טבלאות": "tables_config",
  "כותרת_עליונה": "running_head",
  "כותרת_תחתונה": "running_foot",
  "מסמך": "document",
  "כתב_רשי": "rashi",
  "עיצוב": "styled",
  "הדגשה": "bold",
  "נטוי": "italic",
  "קו_תחתון": "uline",
  "קו_חוצה": "sthrough",
  "סימון": "mark",
  "עילי": "sup",
  "תחתי": "sub_",
  "רברבתי": "scaps",
  "גדול": "big",
  "קטן": "tiny",
  "גודל_גופן": "fsize",
  "צבע": "color",
  "רקע": "bg",
  "מרווח_אותיות": "track",
  "גופן_שונה": "usefont",
  "קוד": "mono",
  "כותרת": "hlevel",
  "כותרת1": "h1",
  "כותרת2": "h2",
  "כותרת3": "h3",
  "כותרת4": "h4",
  "כותרת5": "h5",
  "כותרת6": "h6",
  "שער": "title",
  "תת_שער": "subtitle",
  "כותרת_בהערה": "note_heading",
  "מרכז": "center_",
  "ימין": "right_",
  "שמאל": "left_",
  "מימין_לשמאל": "rtl_",
  "משמאל_לימין": "ltr_",
  "רשימה": "bullets",
  "ממוספרת": "numbered",
  "ממוספרת_עברית": "henum",
  "פריט": "item",
  "רשימת_הגדרות": "deflist",
  "הגדרה": "defitem",
  "תוכן": "toc",
  "הערה": "fnote",
  "הערה_על_הערה": "subnote",
  "הגדרות_הערות_סיום": "endnotes_config",
  "הערתסיום": "endnote",
  "הערות_בסוף": "endnotes",
  "הערות_בסוף_צד": "endnotes_side",
  "הערת_גיליון": "sidenote",
  "עם_הערות_צד": "sidenotes",
  "הגדרות_הערות_צד": "sidenotes_config",
  "הערת_ימין": "noteright",
  "הערת_שמאל": "noteleft",
  "עם_הערות_דו_צד": "twosided",
  "גוף_הערה": "note_body",
  "הערה_בשם": "note_named",
  "גופי_הערות": "note_bodies",
  "סמן": "anchor",
  "הפניה": "xref",
  "טבלה": "mktable",
  "תא": "cell",
  "כותרת_תא": "headcell",
  "מיזוג": "colspan_",
  "ציטוט": "blockquote",
  "הערת_צד": "callout",
  "תיבה": "framebox",
  "אזהרה": "warnbox",
  "הצלחה": "okbox",
  "מקור": "cite_",
  "חסר_הכללה": "missing_include",
  "כלול": "include_part",
  "חסר": "blank",
  "קו_מפריד": "hrule",
  "מרווח": "vspace",
  "רווח_אופקי": "hspace",
  "מעבר_עמוד": "pbreak",
  "מעבר_שורה": "lbreak",
  "מעבר_פסקה": "parabreak",
  "מעבר_טור": "cbreak",
  "הזחה": "indent_",
  "טורים_בלוק": "cols",
  "תמונה": "img",
  "הגדרות_סימונים": "marks_config",
  "הגדרות_ציון": "ref_config",
  "הגדרות_גמרא": "gemara_config",
  "הגדרות_דיבור_המתחיל": "dh_config",
  "הגדרות_פסוק": "verse_config",
  "הגדרות_ציון_מקור": "sourceref_config",
  "הגדרות_ערך": "indexentry_config",
  "הגדרות_מראה_מקום": "sourcenote_config",
  "הגדרות_סימן": "siman_config",
  "הגדרות_סעיף": "seif_config",
  "הגדרות_אות": "os_config",
  "מקור_חי": "livecite",
  "מראה_מקומות": "sources",
  "ערך": "indexentry",
  "מפתח_ענינים": "topicindex",
  "ציון_מקור": "sourceref",
  "מפתח_מקורות": "sourceindex",
  "רשימת_סימונים": "marklist",
  "עם_פירוש": "commentary",
  "הגדרות_סקירה": "review_config",
  "הוספה": "inserted",
  "מחיקה": "deleted",
  "הערת_עורך": "comment_",
  "מקטע_עמוד": "page_section",
  "נוסחה": "formula",
  "נוסחה_בשורה": "iformula",
  "סימן": "siman",
  "סעיף": "seif",
  "אות": "os",
  "פסוק": "verse",
  "מראה_מקום": "sourcenote",
  "ציון": "refmark",
  "דיבור_המתחיל": "dh",
  "גמרא": "gemara",
};

/**
 * The English name of every *parameter*, keyed by its Hebrew one.
 *
 * From the prelude's `_en_params`, which is what makes the pairing: an English
 * alias is not a plain binding but a wrapper that renames its named arguments
 * through that table. An English alias whose parameters are still Hebrew is not
 * English, so a command written into an English document needs this as much as
 * it needs `COMMAND_EN`.
 *
 * Where two English spellings share one Hebrew word (`colour`/`color` → `צבע`)
 * the first the prelude declares is the one here, because going back the other
 * way needs one answer.
 */
export const PARAM_EN: Readonly<Record<string, string>> = {
  "גודל": "size",
  "גופן": "font",
  "צבע": "colour",
  "יישור": "align",
  "רוחב_עמוד": "page_width",
  "גובה_עמוד": "page_height",
  "משקל": "weight",
  "נייר": "paper",
  "שוליים": "margin",
  "שפה": "lang",
  "כיוון": "dir",
  "לרוחב": "landscape",
  "סימן_מים": "watermark",
  "כותרת_עליונה": "header",
  "כותרת_תחתונה": "footer",
  "מספור": "numbering",
  "מספור_עברי": "hebrew_numbering",
  "ריווח_שורות": "leading",
  "ריווח_פסקאות": "para_spacing",
  "הזחה_ראשונה": "first_indent",
  "עמודות": "columns",
  "אזור_הערות": "notes_region",
  "רמה": "level",
  "כותרת": "title",
  "כותרות": "titles",
  "שמות": "names",
  "מאת": "by",
  "עומק": "depth",
  "כיתוב": "caption",
  "רוחב": "width",
  "יחס": "ratio",
  "מידה": "amount",
  "הזחה": "indent",
  "הזחת_גוף": "body_indent",
  "הידוק": "tight",
  "סמן": "marker",
  "התחלה": "start",
  "סגנון": "style",
  "תוויות": "labels",
  "פריסה": "layout",
  "תצוגה": "display",
  "טקסט": "text_",
  "גבהים": "heights",
  "מסגרת": "frame",
  "הערה": "note",
  "ממוספרת": "numbered",
  "זרם": "stream",
  "זרמים": "streams",
  "גוון": "tint",
  "קו": "rule",
  "סוג": "kind",
  "שם": "name",
  "ערוץ": "channel",
  "מיקום": "placement",
  "אזור": "region",
  "גובה": "height",
  "כפה": "force",
  "ריווח": "spacing",
  "מרווח": "inset",
  "ריווח_פריט": "item_spacing",
  "ריווח_בין": "space_between",
  "ריווח_לפני": "space_before",
  "ריווח_אחרי": "space_after",
  "ריווח_מספור": "number_spacing",
  "ריווח_הערות": "note_spacing",
  "קו_בין": "rule_between",
  "מרווח_אותיות": "tracking",
  "קו_תחתון": "underline",
  "רברבתי": "smallcaps",
  "מקור": "source",
  "תת": "sub",
  "מקום": "place",
  "סוגריים": "brackets",
  "קבוצות": "groups",
  "תווים": "chars",
  "מיון": "sort",
  "פטור": "exempt",
  "ברשימה": "listed",
  "צבע_כותרת": "header_fill",
  "צבע_פס": "stripe",
  "פסים": "striped",
  "צבע_הוספה": "insert_colour",
  "צבע_מחיקה": "delete_colour",
  "צבע_הערה": "note_colour",
};

/**
 * Per-command overrides, exactly as the prelude's `extra:` states them.
 *
 * Two Hebrew parameters can share one English word — `טורים` (text columns) and
 * `עמודות` (table columns) are both `columns` — so the commands that need the
 * other reading say so at their own alias, and a reader merges these over
 * `PARAM_EN` the same way `_en` merges `extra` over `_en_params`. Keyed by the
 * **Hebrew** command name, because that is the name a registry snippet carries.
 */
export const PARAM_EN_BY_COMMAND: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "מדור_בדרגה": { "טורים": "columns" },
  "מדור_א": { "טורים": "columns" },
  "מדור_ב": { "טורים": "columns" },
  "מדור_ג": { "טורים": "columns" },
  "מדור_ד": { "טורים": "columns" },
  "מדור_ה": { "טורים": "columns" },
  "מדור_ו": { "טורים": "columns" },
  "מדור_ז": { "טורים": "columns" },
  "הגדרות_מדורגות": { "טורים": "columns" },
  "מדף_בדרגה": { "טורים": "columns" },
  "מדף_א": { "טורים": "columns" },
  "מדף_ב": { "טורים": "columns" },
  "מדף_ג": { "טורים": "columns" },
  "מדף_ד": { "טורים": "columns" },
  "מדף_ה": { "טורים": "columns" },
  "מדף_ו": { "טורים": "columns" },
  "מדף_ז": { "טורים": "columns" },
  "הגדרות_מדפים": { "טורים": "columns" },
  "הערה_זרם": { "טורים": "columns" },
  "הערת_תוכן": { "טורים": "columns" },
  "הערת_מקור": { "טורים": "columns" },
  "הגדרות_זרמים": { "טורים": "columns" },
  "ערוץ": { "טורים": "columns" },
  "כותרת_עליונה": { "זוגי": "even", "אי_זוגי": "odd" },
  "כותרת_תחתונה": { "זוגי": "even", "אי_זוגי": "odd" },
  "מסמך": { "טורים": "columns", "עמודות": "table_columns", "יישור": "justify", "כותרת_מסמך": "title", "שוליים_עליון": "margin_top", "שוליים_תחתון": "margin_bottom", "שוליים_פנימי": "margin_inner", "שוליים_חיצוני": "margin_outer", "שולי_כריכה": "gutter", "דו_צדדי": "two_sided", "כותרת_זוגי": "header_even", "כותרת_אי_זוגי": "header_odd", "תחתונה_זוגי": "footer_even", "תחתונה_אי_זוגי": "footer_odd", "יישור_כותרת": "head_align", "מחבר": "author", "מילות_מפתח": "keywords", "מניעת_יתומים": "prevent_orphans", "ריווח_הערות": "note_spacing" },
  "הערת_גיליון": { "מרווח": "gutter" },
  "הגדרות_הערות_צד": { "מרווח": "gutter" },
  "הערת_ימין": { "מרווח": "gutter" },
  "הערת_שמאל": { "מרווח": "gutter" },
  "הערת_צד": { "קו": "accent" },
  "מפתח_ענינים": { "טורים": "columns" },
  "מפתח_מקורות": { "טורים": "columns" },
  "רשימת_סימונים": { "טורים": "columns" },
  "מקטע_עמוד": { "טורים": "columns" },
};

/** The parameter pairing in force inside a given command, Hebrew → English. */
export function paramsOf(heCommand: string): Readonly<Record<string, string>> {
  const over = PARAM_EN_BY_COMMAND[heCommand];
  return over ? { ...PARAM_EN, ...over } : PARAM_EN;
}

/**
 * Every command whose body is a Typst **container**, in Hebrew.
 *
 * Measured by the engine (`engine/examples/emit-containers.rs`) rather than
 * written down, because it is a fact about what each command's definition
 * expands to: `#כותרת1` is a `heading()` and `#הערה` a `footnote()`, both
 * containers; `#שער` is `align(center, text(…))` and `#הדגשה` a `strong()`,
 * both transparent. Fifty-three of the prelude's bindings are containers and
 * nothing about their names separates them from the rest.
 *
 * Typst refuses `pagebreak()` inside one, in English, from the middle of a
 * blanked preview — so this is what `legalAt` greys the page-level commands on.
 */
export const CONTAINERS: readonly string[] = [
  "הערה_בדרגה",
  "מדור_בדרגה",
  "מדור_א",
  "מדור_ב",
  "מדור_ג",
  "מדור_ד",
  "מדור_ה",
  "מדור_ו",
  "מדור_ז",
  "מדף_בדרגה",
  "מדף_א",
  "מדף_ב",
  "מדף_ג",
  "מדף_ד",
  "מדף_ה",
  "מדף_ו",
  "מדף_ז",
  "הערה_זרם",
  "הערת_תוכן",
  "הערת_מקור",
  "הערה_א",
  "הערה_ב",
  "הערה_ג",
  "הערה_ד",
  "הערה_ה",
  "הערה_ו",
  "הערה_ז",
  "כותרת_עליונה",
  "כותרת_תחתונה",
  "קוד",
  "כותרת",
  "כותרת1",
  "כותרת2",
  "כותרת3",
  "כותרת4",
  "כותרת5",
  "כותרת6",
  "רשימה",
  "ממוספרת",
  "ממוספרת_עברית",
  "רשימת_הגדרות",
  "הגדרה",
  "הערה",
  "הערה_על_הערה",
  "הערת_גיליון",
  "עם_הערות_צד",
  "הערת_ימין",
  "הערת_שמאל",
  "עם_הערות_דו_צד",
  "גופי_הערות",
  "טבלה",
  "ציטוט",
  "הערת_צד",
  "תיבה",
  "אזהרה",
  "הצלחה",
  "חסר_הכללה",
  "כלול",
  "הזחה",
  "טורים_בלוק",
  "סימן",
  "סעיף",
  "מראה_מקום",
  "עם_פירוש",
  "הערת_עורך",
];

/**
 * Which Hebrew characters are marks, which separate words, which fold to what.
 *
 * From `girsa-hebrew` by way of `engine/facts.gen.json`, because a browser tab
 * cannot call a Rust crate. `sefarim.ts`'s `fold` wrote these out by hand and
 * had **one** of the four word-breaking characters — maqaf. Paseq ׀, sof
 * pasuq ׃ and nun hafukha ׆ sit in the same block, separate words the
 * same way, and were being deleted, so `בן׃איש` folded to `בןאיש` and found
 * nothing. Its geresh list was also missing `U+2018`, so a name pasted with a
 * left curly quote folded differently from the same name with a right one.
 *
 * Both were true of the Rust and Typst copies as well. Three implementations of
 * one rule need an oracle, not three careful readings — `engine/tests/one_want.rs`
 * and `test/sefarim.test.mjs` are that oracle — and the *tables* underneath the
 * rule need not be written three times at all.
 */
export const HEBREW = {
  /** ־ maqaf, ׀ paseq, ׃ sof pasuq, ׆ nun hafukha. */
  wordBreaking: "־׀׃׆",
  /** The combining-mark block, inclusive. Everything in it but the four above. */
  markRange: ["֑", "ׇ"] as const,
  /** Every spelling of a geresh, then the one character they fold to. */
  geresh: ["׳'‘’", "'"] as const,
  /** Every spelling of gershayim, then the one they fold to. */
  gershayim: ["״\"“”", "\""] as const,
  /** The letters Hebrew attaches to the front of a word, `ד` included. */
  prefixLetters: "בדהוכלמש",
} as const;

/**
 * Every character Typst reads as markup inside a `[…]` body.
 *
 * From `engine/src/escape.rs`. This side had **five** of them — `\\ [ ] # $` —
 * and `girsa-ksav`'s escaper had ten, and both write `#מראה_מקום(מקור: …)[…]`
 * out of the same Girsa `display` string. The five missing were `*` (strong),
 * `_` (emph), `<` and `>` (a label) and `@` (a ref), all of which appear in
 * Sefaria titles. Same feature, two doors, two documents.
 */
export const MARKUP_ESCAPES = "#[]\\$*_<>@";

/**
 * One template, as the engine's `templates::Template` is shaped.
 *
 * **Generated, and that is the finding.** `api.ts` carried this interface by
 * hand — the one Rust→TypeScript table with none of `facts.gen.json`'s
 * protection. A field added in Rust never reached the client; a field renamed
 * became `undefined` at every use, silently, because the Rust value always
 * wins on the wire. That is the same failure `facts.rs` was written against,
 * still standing in the one table it had not reached.
 *
 * The **field names** cross, not the templates: their bodies are twelve whole
 * documents and `/templates` sends them at runtime. Every field is a string in
 * Rust (`&'static str`), so every field is a string here.
 */
export interface TemplateDef {
  body: string;
  category: string;
  desc_en: string;
  desc_he: string;
  en: string;
  he: string;
  id: string;
  lang: string;
}

/** The same field names as data, for a check that has to run at runtime. */
export const TEMPLATE_FIELDS: readonly string[] = ["body","category","desc_en","desc_he","en","he","id","lang"];

/** A character class matching every Hebrew combining mark but not the four. */
export function markPattern(flags = "gu"): RegExp {
  const hex = (c: string) => (c.codePointAt(0) ?? 0).toString(16);
  const cls = [...HEBREW.wordBreaking].map((c) => `\\u{${hex(c)}}`);
  const [lo, hi] = HEBREW.markRange;
  const range = `\\u{${hex(lo)}}-\\u{${hex(hi)}}`;
  // A negated lookahead rather than a hand-split range: splitting the block
  // around four holes is how `sefarim.ts` came to have one of them.
  return new RegExp(`(?!${cls.join("|")})[${range}]`, flags);
}

/** Both spellings of a command, for a table that must accept either. */
export function bothSpellings(he: string): readonly string[] {
  const en = COMMAND_EN[he];
  return en ? [he, en] : [he];
}

/**
 * Expand a Hebrew-keyed table so it answers to the English aliases too.
 *
 * The pairing comes from the registry, so a command renamed in Rust keeps
 * working here — which is exactly what a hand-written second copy could not do.
 * A name the registry does not know keeps its single key rather than throwing:
 * some entries are prelude-only spellings the palette never offers.
 */
export function withAliases<T>(byHebrew: Record<string, T>): Record<string, T> {
  const out: Record<string, T> = {};
  for (const [he, value] of Object.entries(byHebrew)) {
    for (const name of bothSpellings(he)) out[name] = value;
  }
  return out;
}

/** One embedded thing and the notice it owes. See engine/src/notices.rs. */
export interface BundledNotice {
  readonly kind: "font" | "lexicon";
  readonly name: string;
  readonly copyright: string;
  readonly licence: string;
  readonly url: string;
  /** A text face a writer may choose. False for the maths font, which has no letters. */
  readonly selectable: boolean;
}

export const BUNDLED_NOTICES: readonly BundledNotice[] = [
  { kind: "font", name: "Frank Ruhl Hofshi", copyright: "Copyright 2015 The Frank Ruhl Hofshi Project Authors", licence: "SIL Open Font License 1.1", url: "https://openfontlicense.org", selectable: true },
  { kind: "font", name: "David Libre", copyright: "Copyright (c) 2003–2016 The David Libre Project Authors", licence: "SIL Open Font License 1.1", url: "https://openfontlicense.org", selectable: true },
  { kind: "font", name: "Cascadia Mono", copyright: "Copyright (c) 2020 Microsoft Corporation", licence: "SIL Open Font License 1.1", url: "https://github.com/microsoft/cascadia-code", selectable: true },
  { kind: "font", name: "New Computer Modern Math", copyright: "Copyright (C) 2019–2026 Antonis Tsolomitis", licence: "GUST Font License 1.0 (LPPL 1.3c)", url: "https://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt", selectable: false },
  { kind: "lexicon", name: "English Speller Database (SCOWL)", copyright: "Copyright 2000–2026 Kevin Atkinson; Australian data © 2016 Benjamin Titze", licence: "ESDB licence", url: "https://wordlist.aspell.net", selectable: false },
  { kind: "lexicon", name: "Ksav Hebrew lexicon", copyright: "Built from Public Domain texts (Sefaria, Project Ben-Yehuda)", licence: "MIT OR Apache-2.0", url: "https://github.com/SYKhayyat/ksav", selectable: false },
];

/** The font families the engine bundles and a writer may choose. */
export const BUNDLED_FONTS: readonly string[] = BUNDLED_NOTICES.filter(
  (n) => n.kind === "font" && n.selectable,
).map((n) => n.name);
