// Generated by app/tools/emit-engine.mjs from engine/facts.gen.json
// (the engine's own `DocConfig::default()`, registry and notices, serialised by
// engine/src/facts.rs) and from the prelude's `#let` lines.
// Do not edit by hand: run `node tools/emit-engine.mjs`.
// `npm test` fails when this file and the engine disagree.
//
// Three facts the engine already knows, which this side used to know separately:
// the document defaults, the Hebrew↔English command pairing, and what the engine
// redistributes. See the generator's header for why each is generated rather
// than fetched.

/**
 * The engine's own document defaults, as `DocConfig::default()` states them.
 *
 * The four per-edge margins and the note region are **absent** rather than
 * zero — absent means "follow the uniform margin" / "decide from the document",
 * which is a different instruction from any number. (margin_top_cm, margin_bottom_cm, margin_inner_cm, margin_outer_cm, notes_region_cm)
 */
export const DOC_DEFAULTS = {
  font: "Frank Ruhl Hofshi",
  size_pt: 12,
  margin_cm: 2.5,
  gutter_cm: 0,
  two_sided: false,
  header_even: "",
  header_odd: "",
  footer_even: "",
  footer_odd: "",
  head_align: "center",
  title: "",
  author: "",
  keywords: [],
  pdf_standard: "",
  pdf_tagged: true,
  prevent_orphans: false,
  dir: "rtl",
  numbering: true,
  justify: true,
  line_spacing_em: 0.75,
  para_spacing_em: 1.2,
  first_line_indent_em: 0,
  columns: 1,
  paper: "a4",
  hebrew_numbering: false,
  header: "",
  footer: "",
} as const;

/**
 * The English alias of every command, keyed by its Hebrew name.
 *
 * From the prelude's own `#let` lines, which are what *make* the pairing —
 * so this covers the four tiers per family that the palette registry stops
 * short of, and an export meets a document that used one.
 */
export const COMMAND_EN: Readonly<Record<string, string>> = {
  "הגדרות_הערות": "footnote_config",
  "הערה_בדרגה": "tier",
  "הערה_א": "tier1",
  "הערה_ב": "tier2",
  "הערה_ג": "tier3",
  "הערה_ד": "tier4",
  "הערה_ה": "tier5",
  "הערה_ו": "tier6",
  "הערה_ז": "tier7",
  "מדור_בדרגה": "band",
  "מדור_א": "band1",
  "מדור_ב": "band2",
  "מדור_ג": "band3",
  "מדור_ד": "band4",
  "מדור_ה": "band5",
  "מדור_ו": "band6",
  "מדור_ז": "band7",
  "הערות_מדורגות": "banded_notes",
  "הגדרות_מדורגות": "banded_config",
  "מדף_בדרגה": "pageband",
  "מדף_א": "pageband1",
  "מדף_ב": "pageband2",
  "מדף_ג": "pageband3",
  "מדף_ד": "pageband4",
  "מדף_ה": "pageband5",
  "מדף_ו": "pageband6",
  "מדף_ז": "pageband7",
  "הגדרות_מדפים": "pagebands_config",
  "הערה_זרם": "stream_note",
  "הערת_תוכן": "contentnote",
  "הערת_מקור": "sourcenote_stream",
  "הגדרות_זרמים": "streams_config",
  "הגדרות_כותרות": "headings_config",
  "הגדרות_רשימות": "lists_config",
  "הגדרות_טבלאות": "tables_config",
  "מסמך": "document",
  "כתב_רשי": "rashi",
  "הדגשה": "bold",
  "נטוי": "italic",
  "קו_תחתון": "uline",
  "קו_חוצה": "sthrough",
  "סימון": "mark",
  "עילי": "sup",
  "תחתי": "sub_",
  "רברבתי": "scaps",
  "גדול": "big",
  "קטן": "tiny",
  "גודל_גופן": "fsize",
  "צבע": "color",
  "רקע": "bg",
  "מרווח_אותיות": "track",
  "גופן_שונה": "usefont",
  "קוד": "mono",
  "כותרת1": "h1",
  "כותרת2": "h2",
  "כותרת3": "h3",
  "כותרת4": "h4",
  "כותרת5": "h5",
  "כותרת6": "h6",
  "שער": "title",
  "תת_שער": "subtitle",
  "כותרת_בהערה": "note_heading",
  "מרכז": "center_",
  "ימין": "right_",
  "שמאל": "left_",
  "מימין_לשמאל": "rtl_",
  "משמאל_לימין": "ltr_",
  "רשימה": "bullets",
  "ממוספרת": "numbered",
  "ממוספרת_עברית": "henum",
  "פריט": "item",
  "רשימת_הגדרות": "deflist",
  "הגדרה": "defitem",
  "תוכן": "toc",
  "הערה": "fnote",
  "הערה_על_הערה": "subnote",
  "הגדרות_הערות_סיום": "endnotes_config",
  "הערתסיום": "endnote",
  "הערות_בסוף": "endnotes",
  "הערות_בסוף_צד": "endnotes_side",
  "הערת_גיליון": "sidenote",
  "עם_הערות_צד": "sidenotes",
  "הגדרות_הערות_צד": "sidenotes_config",
  "הערת_ימין": "noteright",
  "הערת_שמאל": "noteleft",
  "עם_הערות_דו_צד": "twosided",
  "גוף_הערה": "note_body",
  "הערה_בשם": "note_named",
  "גופי_הערות": "note_bodies",
  "סמן": "anchor",
  "הפניה": "xref",
  "טבלה": "mktable",
  "תא": "cell",
  "כותרת_תא": "headcell",
  "מיזוג": "colspan_",
  "ציטוט": "blockquote",
  "הערת_צד": "callout",
  "תיבה": "framebox",
  "אזהרה": "warnbox",
  "הצלחה": "okbox",
  "מקור": "cite_",
  "חסר_הכללה": "missing_include",
  "כלול": "include_part",
  "חסר": "blank",
  "קו_מפריד": "hrule",
  "מרווח": "vspace",
  "רווח_אופקי": "hspace",
  "מעבר_עמוד": "pbreak",
  "מעבר_שורה": "lbreak",
  "מעבר_טור": "cbreak",
  "הזחה": "indent_",
  "טורים_בלוק": "cols",
  "תמונה": "img",
  "מקור_חי": "livecite",
  "מראה_מקומות": "sources",
  "ערך": "indexentry",
  "מפתח_ענינים": "topicindex",
  "ציון_מקור": "sourceref",
  "מפתח_מקורות": "sourceindex",
  "עם_פירוש": "commentary",
  "הגדרות_סקירה": "review_config",
  "הוספה": "inserted",
  "מחיקה": "deleted",
  "הערת_עורך": "comment_",
  "מקטע_עמוד": "page_section",
  "נוסחה": "formula",
  "נוסחה_בשורה": "iformula",
  "סימן": "siman",
  "סעיף": "seif",
  "אות": "osource",
  "פסוק": "verse",
  "מראה_מקום": "sourcenote",
  "ציון": "refmark",
  "דיבור_המתחיל": "dh",
  "גמרא": "gemara",
  "כותרת": "hlevel",
};

/** Both spellings of a command, for a table that must accept either. */
export function bothSpellings(he: string): readonly string[] {
  const en = COMMAND_EN[he];
  return en ? [he, en] : [he];
}

/**
 * Expand a Hebrew-keyed table so it answers to the English aliases too.
 *
 * The pairing comes from the registry, so a command renamed in Rust keeps
 * working here — which is exactly what a hand-written second copy could not do.
 * A name the registry does not know keeps its single key rather than throwing:
 * some entries are prelude-only spellings the palette never offers.
 */
export function withAliases<T>(byHebrew: Record<string, T>): Record<string, T> {
  const out: Record<string, T> = {};
  for (const [he, value] of Object.entries(byHebrew)) {
    for (const name of bothSpellings(he)) out[name] = value;
  }
  return out;
}

/** One embedded thing and the notice it owes. See engine/src/notices.rs. */
export interface BundledNotice {
  readonly kind: "font" | "lexicon";
  readonly name: string;
  readonly copyright: string;
  readonly licence: string;
  readonly url: string;
  /** A text face a writer may choose. False for the maths font, which has no letters. */
  readonly selectable: boolean;
}

export const BUNDLED_NOTICES: readonly BundledNotice[] = [
  { kind: "font", name: "Frank Ruhl Hofshi", copyright: "Copyright 2015 The Frank Ruhl Hofshi Project Authors", licence: "SIL Open Font License 1.1", url: "https://openfontlicense.org", selectable: true },
  { kind: "font", name: "David Libre", copyright: "Copyright (c) 2003–2016 The David Libre Project Authors", licence: "SIL Open Font License 1.1", url: "https://openfontlicense.org", selectable: true },
  { kind: "font", name: "Cascadia Mono", copyright: "Copyright (c) 2020 Microsoft Corporation", licence: "SIL Open Font License 1.1", url: "https://github.com/microsoft/cascadia-code", selectable: true },
  { kind: "font", name: "New Computer Modern Math", copyright: "Copyright (C) 2019–2026 Antonis Tsolomitis", licence: "GUST Font License 1.0 (LPPL 1.3c)", url: "https://tug.org/fonts/licenses/GUST-FONT-LICENSE.txt", selectable: false },
  { kind: "lexicon", name: "English Speller Database (SCOWL)", copyright: "Copyright 2000–2026 Kevin Atkinson; Australian data © 2016 Benjamin Titze", licence: "ESDB licence", url: "https://wordlist.aspell.net", selectable: false },
  { kind: "lexicon", name: "Ksav Hebrew lexicon", copyright: "Built from Public Domain texts (Sefaria, Project Ben-Yehuda)", licence: "MIT OR Apache-2.0", url: "https://github.com/SYKhayyat/ksav", selectable: false },
];

/** The font families the engine bundles and a writer may choose. */
export const BUNDLED_FONTS: readonly string[] = BUNDLED_NOTICES.filter(
  (n) => n.kind === "font" && n.selectable,
).map((n) => n.name);
