// Generated by app/tools/emit-services.mjs from engine/facts.gen.json,
// which engine/src/facts.rs serialises out of engine/src/services.rs.
// Do not edit by hand: run `node tools/emit-services.mjs`.
// `npm test` fails when this file and the engine's registry disagree.
//
// This is the client half of one registry. The engine routes HTTP from the same
// table, the wasm module dispatches its single `ksav_call` export from it, and
// the desktop shell's single `ksav_call` command looks names up in it — so a
// service reaches all four builds by being added once, in Rust.

/** Every service the engine can be asked for. A typo here is a `tsc` error. */
export type ServiceName = "compile" | "assemble" | "jump" | "reveal" | "spell" | "suggest" | "commands" | "templates" | "sefarim" | "inbox" | "mekoros" | "linkify" | "refresh";

export interface ServiceDef {
  readonly name: ServiceName;
  /** How the HTTP builds reach it. The wasm and desktop builds call by name. */
  readonly method: "GET" | "POST";
  readonly path: string;
  /** `layout` lays the document out — the server caps these and the desktop
   *  app runs them off the UI thread. See `Cost` in engine/src/services.rs. */
  readonly cost: "layout" | "work" | "quick";
  /** Needs the loopback to Girsa, which a browser tab has no way to reach. */
  readonly nativeOnly: boolean;
}

export const SERVICES: readonly ServiceDef[] = [
  { name: "compile", method: "POST", path: "/compile", cost: "layout", nativeOnly: false },
  { name: "assemble", method: "POST", path: "/assemble", cost: "quick", nativeOnly: false },
  { name: "jump", method: "POST", path: "/jump", cost: "layout", nativeOnly: false },
  { name: "reveal", method: "POST", path: "/reveal", cost: "layout", nativeOnly: false },
  { name: "spell", method: "POST", path: "/spell", cost: "work", nativeOnly: false },
  { name: "suggest", method: "POST", path: "/suggest", cost: "work", nativeOnly: false },
  { name: "commands", method: "GET", path: "/commands", cost: "quick", nativeOnly: false },
  { name: "templates", method: "GET", path: "/templates", cost: "quick", nativeOnly: false },
  { name: "sefarim", method: "GET", path: "/sefarim", cost: "quick", nativeOnly: false },
  { name: "inbox", method: "POST", path: "/inbox", cost: "quick", nativeOnly: true },
  { name: "mekoros", method: "POST", path: "/mekoros", cost: "work", nativeOnly: true },
  { name: "linkify", method: "POST", path: "/linkify", cost: "work", nativeOnly: true },
  { name: "refresh", method: "POST", path: "/refresh", cost: "work", nativeOnly: true },
];

/** The path each service answers on, for the two builds that speak HTTP. */
export const SERVICE_PATH: Readonly<Record<ServiceName, string>> = Object.fromEntries(
  SERVICES.map((s) => [s.name, s.path]),
) as Record<ServiceName, string>;

/**
 * The whole definition, by name — which is what an HTTP caller actually needs.
 *
 * `SERVICE_PATH` alone was half the answer, and the missing half cost a working
 * feature: `api.ts` took the path from here and the *verb* from which of its two
 * private helpers a call site happened to use. `/inbox` was moved to POST in the
 * engine for a real reason — as a GET it was drainable by
 * `<img src="http://localhost:7878/inbox">`, which sends no Origin, so no CORS
 * check anywhere could have refused it — and the client kept asking for it with
 * GET. The server answered 404, the poll swallowed it, and the Girsa handoff was
 * dead on a path where both ends were correct.
 */
export const SERVICE: Readonly<Record<ServiceName, ServiceDef>> = Object.fromEntries(
  SERVICES.map((s) => [s.name, s]),
) as Record<ServiceName, ServiceDef>;
