// Generated by app/tools/emit-svg-vocabulary.mjs from
// engine/tests/fixtures/svg-vocabulary.json — every template compiled by
// engine/examples/emit-svg-vocabulary.rs, every page scanned.
//
// Do not edit by hand: run `node tools/emit-svg-vocabulary.mjs`. `npm test`
// fails when this file and the measurement disagree.

/**
 * Every element name in a page of engine SVG, measured.
 *
 * `a` is here because Typst emits an `<a>` with a transparent `<rect>` and no
 * `href` of its own for a link's hit area. It is the one name on this list that
 * nobody would have written down, and its absence would have dropped every link
 * in every document silently.
 */
export const SVG_ELEMENTS: readonly string[] = [
  "a",
  "clipPath",
  "defs",
  "g",
  "image",
  "path",
  "rect",
  "svg",
  "symbol",
  "use",
];

/**
 * Every attribute name in a page of engine SVG, measured.
 *
 * `xmlns`, `xmlns:xlink` and `xmlns:h5` because the exporter writes them on
 * every root and a document without its namespace declaration is not an SVG
 * document. `overflow` because Typst writes it to clip page content to the media
 * box, and dropping it changes what a page *looks* like rather than what it
 * contains — which is a quieter failure than a missing element.
 */
export const SVG_ATTRIBUTES: readonly string[] = [
  "clip-path",
  "d",
  "fill",
  "fill-rule",
  "height",
  "id",
  "overflow",
  "preserveAspectRatio",
  "stroke",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-miterlimit",
  "stroke-width",
  "transform",
  "viewBox",
  "width",
  "x",
  "xlink:href",
  "xmlns",
  "xmlns:h5",
  "xmlns:xlink",
  "y",
];
