;;; ksav-services.el --- The engine's services  -*- lexical-binding: t; -*-

;; Generated by ksav/app/tools/emit-emacs.mjs from engine/facts.gen.json,
;; which engine/src/facts.rs serialises out of engine/src/services.rs.
;; Do not edit by hand: run `node tools/emit-emacs.mjs' in ksav/app.
;; `npm test' fails when this file and the engine's registry disagree.

;;; Commentary:

;; The Emacs client's half of one registry.  The engine routes HTTP from the
;; same table, the wasm module dispatches its single export from it, the desktop
;; shell looks names up in it, and the browser client is generated from it — so
;; a service reaches all five by being added once, in Rust.
;;
;; Ksav's own history is the argument for generating this.  When these lists
;; were written by hand there were four of them and they had drifted: `sefarim'
;; was in three and missing from the fourth, so citation autocomplete was simply
;; dead in one build with nothing anywhere reporting it.

;;; Code:

(defconst ksav-services
  '(
    ("compile" "POST" "/compile" nil)
    ("assemble" "POST" "/assemble" nil)
    ("jump" "POST" "/jump" nil)
    ("reveal" "POST" "/reveal" nil)
    ("spell" "POST" "/spell" nil)
    ("suggest" "POST" "/suggest" nil)
    ("commands" "GET" "/commands" nil)
    ("templates" "GET" "/templates" nil)
    ("sefarim" "GET" "/sefarim" nil)
    ("inbox" "POST" "/inbox" t)
    ("mekoros" "POST" "/mekoros" t)
    ("linkify" "POST" "/linkify" t)
    ("refresh" "POST" "/refresh" t)
    ("clipboard-source" "POST" "/clipboard-source" t)
    ("saved-here" "POST" "/saved-here" t)
    ("git" "POST" "/git" t))
  "Every service the engine answers: name, method, path, and needs-the-machine.

The fourth column is `Reach::Native' in the engine registry — a service
that needs the installed application, either for the loopback to Girsa or for a
folder on disk.  It is carried so that a client can tell \"this engine cannot do
that\" from \"something went wrong\", which are different sentences.")

(defun ksav-service (name)
  "The row for NAME, or an error naming it.

An error rather than nil: every caller in this package spells a service name as
a literal, so a name nothing answers is a typo in elisp and not a state a reader
can be in.  Returning nil would turn it into a URL of \"nil\" and a 404."
  (or (assoc name ksav-services)
      (error "Ksav: no engine service named %s" name)))

(defun ksav-service-path (name)
  "The HTTP path service NAME answers on."
  (nth 2 (ksav-service name)))

(defun ksav-service-method (name)
  "The HTTP method service NAME wants, as a string."
  (nth 1 (ksav-service name)))

(defun ksav-service-native-p (name)
  "Does service NAME need the installed application?"
  (and (nth 3 (ksav-service name)) t))

(defconst ksav-git-operations
  '(
    "status"
    "init"
    "log"
    "show"
    "commit"
    "who"
    "restore"
    "revert"
    "branches"
    "switch"
    "merge"
    "merge-abort"
    "resolve"
    "remotes"
    "remote-add"
    "fetch"
    "pull"
    "push")
  "Every operation the `git' service answers.

One service carrying an `op', so this is the same registry one level down:
`OPERATIONS' in engine/src/git.rs is the list, and an operation this package
spells wrong is an error at the call rather than a refusal a writer is shown.")

(provide 'ksav-services)
;;; ksav-services.el ends here
