;;; ksav-release.el --- Where a Ksav engine comes from  -*- lexical-binding: t; -*-

;; Generated by ksav/app/tools/emit-release-assets.mjs, which is also where
;; .github/workflows/release.yml gets its build matrix.
;; Do not edit by hand: run `node tools/emit-release-assets.mjs' in ksav/app.
;; `npm test' fails when this file and that table disagree.

;;; Commentary:

;; The engine binaries a Ksav release attaches, and how this machine recognises
;; the one that is for it.  `ksav-install-engine' in `ksav.el' is the caller.
;;
;; Generated for the same reason `ksav-services.el' is.  These names are agreed
;; between a workflow that uploads files and elisp that downloads them, and
;; nothing about a disagreement is visible until somebody's install fails with a
;; 404 — which is precisely the class of silent drift this product has already
;; paid for four times over in four other languages.

;;; Code:

(require 'seq)

(defconst ksav-release-targets
  '(
    ("windows-x86_64" windows-nt ("x86_64") "ksav-engine-windows-x86_64.exe" "ksav.exe")
    ("linux-x86_64" gnu/linux ("x86_64") "ksav-engine-linux-x86_64" "ksav")
    ("macos-aarch64" darwin ("aarch64" "arm64") "ksav-engine-macos-aarch64" "ksav")
    ("macos-x86_64" darwin ("x86_64") "ksav-engine-macos-x86_64" "ksav"))
  "Every platform a Ksav release carries an engine for.

Each row is: an identifier, the `system-type' it is for, the architectures it
answers to as spelt in the first field of `system-configuration', the asset's
name on the release page, and what the binary should be called once it is on
disk.")

(defun ksav-release-arch ()
  "This machine's architecture, as `system-configuration' spells it."
  (car (split-string system-configuration "-")))

(defun ksav-release-this-machine ()
  "The row in `ksav-release-targets' for the machine running this Emacs.

Nil when there is none — a platform Ksav does not publish an engine for is a
real answer, and the caller says so by name rather than downloading something
that cannot run."
  (let ((arch (ksav-release-arch)))
    (seq-find (lambda (row)
                (and (eq system-type (nth 1 row))
                     (member arch (nth 2 row))))
              ksav-release-targets)))

(defun ksav-release-asset (row)
  "The name asset ROW has on the release page."
  (nth 3 row))

(defun ksav-release-binary (row)
  "What the binary in ROW should be called once it is on disk."
  (nth 4 row))

(provide 'ksav-release)
;;; ksav-release.el ends here
