// Write the Emacs package's copy of the engine's service registry, from the
// engine's.
//
// The fifth target. The engine registry in services.rs opens with the count of
// registry had already cost this product — a service missing from one of four
// dispatch tables, a dev proxy with five of twelve routes, thirteen Tauri
// command names for eleven functions — and every one of those failures was
// silent. `editors/emacs/ksav.el` talks to the same engine over the same HTTP,
// so it needs the same table, and writing it by hand in elisp would be the
// fifth copy to drift.
//
// It is a *small* table here on purpose. The elisp needs the name, the method
// and the path, and nothing else: `cost` is how a delivery target decides
// whether to offload the call, and this client has one thread and makes every
// call synchronously, so carrying it would be carrying a fact it cannot act on.
// `nativeOnly` is carried, because it is the difference between "this engine
// cannot do that" and "something went wrong", and a client that cannot tell
// those apart reports the first as the second.
//
//   node tools/emit-emacs.mjs          # rewrite
//   node tools/emit-emacs.mjs --check  # fail if stale
//
// `npm test` runs the check, so a service added in Rust and not regenerated
// here is a red suite rather than an Emacs command that 404s.

import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { runAsScript } from "./generated.mjs";
import { facts, ARTEFACT } from "./facts.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "editors", "emacs", "ksav-services.el");

function read() {
  const services = facts().services.map((s) => ({
    name: s.name,
    method: s.method.toUpperCase(),
    path: s.path,
    nativeOnly: s.reach === "native",
  }));
  // The `git` service carries an `op`, so the same registry idea one level
  // down: `OPERATIONS` in `engine/src/git.rs` is the list, and an elisp command
  // wired to an operation that is not in it is an error at the call rather than
  // a refusal shown to a writer.
  const gitOps = facts().git_ops ?? [];
  if (services.length < 2 || gitOps.length < 2) {
    console.error(
      `read ${services.length} services and ${gitOps.length} git operations out of ${ARTEFACT}\n` +
        "Regenerate it with:\n  KSAV_BLESS=1 cargo test --test facts   (in ksav/engine)",
    );
    process.exit(1);
  }
  return { services, gitOps };
}

/** An elisp string literal. */
const q = (s) => JSON.stringify(s);

function emit({ services, gitOps }) {
  const rows = services
    .map((s) => `    ("${s.name}" "${s.method}" "${s.path}" ${s.nativeOnly ? "t" : "nil"})`)
    .join("\n");
  const ops = gitOps.map((op) => `    ${q(op)}`).join("\n");
  return `;;; ksav-services.el --- The engine's services  -*- lexical-binding: t; -*-

;; Generated by ksav/app/tools/emit-emacs.mjs from engine/facts.gen.json,
;; which engine/src/facts.rs serialises out of engine/src/services.rs.
;; Do not edit by hand: run \`node tools/emit-emacs.mjs' in ksav/app.
;; \`npm test' fails when this file and the engine's registry disagree.

;;; Commentary:

;; The Emacs client's half of one registry.  The engine routes HTTP from the
;; same table, the wasm module dispatches its single export from it, the desktop
;; shell looks names up in it, and the browser client is generated from it — so
;; a service reaches all five by being added once, in Rust.
;;
;; Ksav's own history is the argument for generating this.  When these lists
;; were written by hand there were four of them and they had drifted: \`sefarim'
;; was in three and missing from the fourth, so citation autocomplete was simply
;; dead in one build with nothing anywhere reporting it.

;;; Code:

(defconst ksav-services
  '(
${rows})
  "Every service the engine answers: name, method, path, and needs-the-machine.

The fourth column is \`Reach::Native' in the engine registry — a service
that needs the installed application, either for the loopback to Girsa or for a
folder on disk.  It is carried so that a client can tell \\\"this engine cannot do
that\\\" from \\\"something went wrong\\\", which are different sentences.")

(defun ksav-service (name)
  "The row for NAME, or an error naming it.

An error rather than nil: every caller in this package spells a service name as
a literal, so a name nothing answers is a typo in elisp and not a state a reader
can be in.  Returning nil would turn it into a URL of \\\"nil\\\" and a 404."
  (or (assoc name ksav-services)
      (error "Ksav: no engine service named %s" name)))

(defun ksav-service-path (name)
  "The HTTP path service NAME answers on."
  (nth 2 (ksav-service name)))

(defun ksav-service-method (name)
  "The HTTP method service NAME wants, as a string."
  (nth 1 (ksav-service name)))

(defun ksav-service-native-p (name)
  "Does service NAME need the installed application?"
  (and (nth 3 (ksav-service name)) t))

(defconst ksav-git-operations
  '(
${ops})
  "Every operation the \`git' service answers.

One service carrying an \`op', so this is the same registry one level down:
\`OPERATIONS' in engine/src/git.rs is the list, and an operation this package
spells wrong is an error at the call rather than a refusal a writer is shown.")

(provide 'ksav-services)
;;; ksav-services.el ends here
`;
}

const built = emit(read());

export const OUTPUTS = [[OUT, built, "editors/emacs/ksav-services.el"]];

runAsScript(import.meta.url, OUTPUTS, "emacs services", "node tools/emit-emacs.mjs");

// `q` is exported so the shape of an elisp literal has one definition if this
// file grows a second table.
export { q };
