//! What the Notes chooser writes, rendered.
//!
//! `apparatus.rs` proves that *hand-written* apparatus markup lays out
//! correctly. `app/test/deferred.test.mjs` proves the chooser emits a
//! well-formed source. Between those two sat the bug nobody could see: the
//! chooser wrote a layout's configuration line at the end of the file, and a
//! Typst `state.update` read from a page footer takes effect on the pages
//! *after* it — so fixed band heights applied to the last page of a sefer and
//! no other. Both test suites were green. The page was wrong.
//!
//! So this suite renders the app's own output. The fixture is generated by
//! `app/tools/emit-note-fixtures.mjs`, which `npm test` also checks for
//! staleness, so the two sides cannot drift apart in silence.
//!
//! The assertions are deliberately about *reaching the reader*: a note whose
//! prose never appears on any page is the failure mode every one of these
//! layouts has had at least once, and it is invisible to `compile().ok()`.

use ksav_engine::probe::{self, TextRun};
use ksav_engine::DocConfig;

const FIXTURE: &str = include_str!("fixtures/note-layouts.json");

struct Case {
    id: String,
    which: String,
    source: String,
    bodies: Vec<String>,
    head: Option<String>,
    exercises_head: bool,
    /// "page", "end", or nothing to assert.
    place: Option<String>,
}

/// A dependency-free read of the two-level fixture — the crate has no JSON
/// dependency and this file is generated, not hand-edited.
fn cases() -> Vec<Case> {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    v["cases"]
        .as_array()
        .expect("cases array")
        .iter()
        .map(|c| Case {
            id: c["id"].as_str().unwrap().to_string(),
            which: c["which"].as_str().unwrap().to_string(),
            source: c["source"].as_str().unwrap().to_string(),
            bodies: c["bodies"]
                .as_array()
                .unwrap()
                .iter()
                .map(|b| b.as_str().unwrap().to_string())
                .collect(),
            head: c["head"].as_str().map(|s| s.to_string()),
            exercises_head: c["exercisesHead"].as_bool().unwrap_or(false),
            place: c["place"].as_str().map(|s| s.to_string()),
        })
        .collect()
}

fn last_body() -> String {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    v["lastBody"].as_str().expect("lastBody").to_string()
}

fn render(body: &str) -> (Vec<TextRun>, usize) {
    let doc = probe::layout(body, &DocConfig::default())
        .unwrap_or_else(|d| panic!("compile failed: {d:?}"));
    let runs = probe::text_runs(&doc);
    let pages = probe::page_sizes(&doc).len();
    (runs, pages)
}

fn page_of(runs: &[TextRun], needle: &str) -> Option<usize> {
    probe::lines(runs, 1.0)
        .iter()
        .find(|l| l.contains(needle))
        .map(|l| l.page)
}

/// Every layout the chooser offers compiles, and both of its notes reach a page.
///
/// "Collected and then never rendered" is the single most common way one of
/// these looks broken, and it is exactly what a compile-only test cannot see.
#[test]
fn every_chooser_layout_puts_its_notes_on_a_page() {
    for c in cases() {
        let (runs, pages) = render(&c.source);
        assert!(
            pages >= 2,
            "{}/{}: the fixture is meant to break over pages, got {pages}",
            c.id,
            c.which
        );
        for body in &c.bodies {
            assert!(
                page_of(&runs, body).is_some(),
                "{}/{}: the note {body:?} was written and never rendered on any page",
                c.id,
                c.which,
            );
        }
    }
}

/// An apparatus prints where the chooser says it prints.
///
/// The assertion that was missing, and the reason a writer could pick "two
/// separate blocks" and get a band sitting near the *top* of the page. Both
/// mechanisms are correct: `#מדף_א`/`#מדף_ב` render from the page footer and
/// `#הערות_מדורגות` renders in the main flow, which means it lands wherever the
/// prose stops. On a short document those look like the same feature, one of
/// them broken. Nothing in the twelve cards distinguished them, and nothing in
/// the suite asked *where* — only whether the text reached a page at all, which
/// it did.
///
/// "foot of the page" is the bottom third. "at the end" is after the last line
/// of body text, in reading order.
#[test]
fn an_apparatus_prints_where_the_chooser_says_it_does() {
    let tail = last_body();
    let mut checked = 0;
    for c in cases() {
        let Some(place) = c.place.as_deref() else {
            continue;
        };
        let doc = probe::layout(&c.source, &DocConfig::default())
            .unwrap_or_else(|d| panic!("{}/{}: compile failed: {d:?}", c.id, c.which));
        let runs = probe::text_runs(&doc);
        let heights = probe::page_sizes(&doc);
        let lines = probe::lines(&runs, 1.0);
        let end = lines
            .iter()
            .filter(|l| l.contains(&tail))
            .map(|l| (l.page, l.y))
            .next_back()
            .unwrap_or_else(|| panic!("{}/{}: the body text is not on any page", c.id, c.which));

        for body in &c.bodies {
            let l = lines
                .iter()
                .find(|l| l.contains(body))
                .unwrap_or_else(|| panic!("{}/{}: {body:?} rendered nowhere", c.id, c.which));
            let height = heights[l.page - 1].1;
            match place {
                "page" => assert!(
                    l.y > height * 2.0 / 3.0,
                    "{}/{}: this layout prints at the foot of the page, and {body:?} is at \
                     y={:.0} of {height:.0} on page {}",
                    c.id,
                    c.which,
                    l.y,
                    l.page,
                ),
                "end" => assert!(
                    (l.page, l.y) > end,
                    "{}/{}: this layout collects to the end, and {body:?} is at page {} y={:.0}, \
                     which is not after the last body line (page {} y={:.0})",
                    c.id,
                    c.which,
                    l.page,
                    l.y,
                    end.0,
                    end.1,
                ),
                other => panic!("unknown place {other:?}"),
            }
            checked += 1;
        }
    }
    assert!(
        checked >= 8,
        "only {checked} placements asserted — is `place` being emitted?"
    );
}

/// A layout's configuration line reaches the pages it is meant to configure.
///
/// This is the regression test for the head/tail bug. It does not need to know
/// what each setting does: it renders the chooser's own output, then renders the
/// same document with the configuration line moved to the end — where it used to
/// be written — and requires the two to differ. If they do not, either the
/// setting is inert (so writing it is a lie) or it is position-independent (so
/// `head` is the wrong field for it). Both are worth failing on.
#[test]
fn a_layouts_configuration_is_written_where_it_takes_effect() {
    // Both `continue`s below are ordinary — most cases carry no configuration
    // line, and only some of those are ones a move can be shown to disturb. But
    // a loop whose every case is skipped is a green test that checked nothing,
    // and this one is two `continue`s away from that: rename `head` in the
    // chooser's output and every case takes the first one.
    let (mut with_head, mut moved) = (0, 0);
    for c in cases() {
        let Some(head) = c.head.as_deref() else {
            continue;
        };
        with_head += 1;
        assert!(
            c.source.starts_with(head),
            "{}/{}: the configuration line is not at the top of the file",
            c.id,
            c.which
        );
        if !c.exercises_head {
            continue;
        }
        moved += 1;
        let at_head = c.source.clone();
        let at_tail = format!(
            "{}\n\n{head}\n",
            c.source.strip_prefix(head).unwrap().trim_start()
        );

        let (head_runs, _) = render(&at_head);
        let (tail_runs, _) = render(&at_tail);

        // Compare every note's rendered line — page, y, x and the text itself.
        // Two lessons are baked in here. Text and x, because a numbering scheme
        // or a tier indent changes what a line says and where it starts without
        // moving it down the page at all; comparing y alone passed a layout
        // whose settings were doing nothing. And *every* note rather than the
        // first, because in a two-layer layout it is the second layer the
        // settings exist to distinguish.
        let lines_of = |runs: &[TextRun], label: &str| {
            c.bodies
                .iter()
                .map(|body| {
                    probe::lines(runs, 1.0)
                        .into_iter()
                        .find(|l| l.contains(body))
                        .map(|l| {
                            (
                                l.page,
                                (l.y * 10.0).round(),
                                (l.runs[0].x * 10.0).round(),
                                l.text(),
                            )
                        })
                        .unwrap_or_else(|| {
                            panic!("{}/{}: {body:?} missing at {label}", c.id, c.which)
                        })
                })
                .collect::<Vec<_>>()
        };
        let hy = lines_of(&head_runs, "head");
        let ty = lines_of(&tail_runs, "tail");

        assert_ne!(
            hy, ty,
            "{}/{}: moving {head:?} to the end of the file changed nothing, so writing it \
             at the top is not what makes it work — check whether the setting is inert",
            c.id, c.which,
        );
    }
    assert!(
        with_head > 0,
        "no case carries a configuration line, so nothing above ran. Either the \
         chooser stopped emitting `head` or the field was renamed."
    );
    assert!(
        moved > 0,
        "{with_head} cases carry a configuration line and none of them is marked \
         `exercises_head`, so the head/tail comparison — the whole regression this \
         test is — never ran."
    );
}
