//! Every command, at every kind of caret position, compiled.
//!
//! `registry.rs` used to compile each snippet standalone and in three fixed
//! nestings — and that is not where the writer is. It is gone now and its two
//! surviving tests are at the bottom of this file; the reason it is gone is
//! written out there.
//!
//! The writer is *between two list items*, and
//! there the editor wrote markup that would not compile — for every command in
//! the registry, without exception, in three separate positions. 384 of 1,026
//! documents failed the first time this grid was swept, and every test in the
//! suite was green.
//!
//! The fixture is generated by `app/tools/emit-insertion-fixtures.mjs`, which
//! runs the app's own insertion path (`insertionAt`) — not a re-implementation
//! of it — and `npm test` checks it for staleness so the two sides cannot drift.
//!
//! Two assertions, and the second is the one that keeps the first honest:
//!
//!   1. everything the product offers here must compile
//!   2. everything the product greys out here must genuinely fail
//!
//! Without (2) the cheapest way to green is to grey the whole toolbar.

use ksav_engine::probe;
use ksav_engine::DocConfig;

const FIXTURE: &str = include_str!("fixtures/insertions.json");

struct Case {
    ctx: String,
    /// Which language's document this position is in.
    lang: String,
    cmd: String,
    en: String,
    legal: bool,
    reason: Option<String>,
    source: String,
}

fn cases() -> Vec<Case> {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    v["cases"]
        .as_array()
        .expect("cases array")
        .iter()
        .map(|c| Case {
            ctx: c["ctx"].as_str().unwrap().to_string(),
            lang: c["lang"].as_str().unwrap().to_string(),
            cmd: c["cmd"].as_str().unwrap().to_string(),
            en: c["en"].as_str().unwrap().to_string(),
            legal: c["legal"].as_bool().unwrap(),
            reason: c["reason"].as_str().map(str::to_string),
            source: c["source"].as_str().unwrap().to_string(),
        })
        .collect()
}

fn compiles(source: &str) -> Result<(), String> {
    match probe::layout(source, &DocConfig::default()) {
        Ok(_) => Ok(()),
        Err(d) => Err(format!("{d:?}")),
    }
}

// The badge the engine draws on a structural child that reached the page with
// no list or table around it comes from `common::has_badge`, and deliberately
// not from a local `&str`. See `engine/tests/children.rs`: the prelude draws it
// in the document's own language, and every document in this grid is laid out
// with `DocConfig::default()`, which is Hebrew. A constant holding the English
// half would turn both assertions below into assertions that cannot fail.
mod common;

/// What a source actually put on the page, or `None` if it did not compile.
fn page_text(source: &str) -> Option<String> {
    let doc = probe::layout(source, &DocConfig::default()).ok()?;
    Some(
        probe::text_runs(&doc)
            .iter()
            .map(|r| r.text.as_str())
            .collect(),
    )
}

/// Whether a refusal for this reason is a claim about compiling or about sense.
///
/// `legalAt` used to answer one question — *would Typst reject this here* — so
/// the grid could settle every refusal by compiling it. It now answers two.
/// `#פריט` outside a list compiles perfectly well; it is wrong for a different
/// reason, and the engine says so by drawing a badge rather than by failing.
///
/// Conflating the two would have cost the test its teeth in either direction:
/// demanding a compile failure would have called 168 correct refusals
/// over-refusal, and dropping the demand would have let *any* refusal through
/// unexamined, which is the "grey the whole toolbar" hole the assertion exists
/// to close. So the reason chooses the evidence, and both kinds stay falsifiable.
fn refusal_must_show_a_badge(reason: Option<&str>) -> bool {
    reason == Some("illegalChildOutside")
}

/// Nothing the editor offers may produce markup that will not compile.
#[test]
fn every_offered_insertion_compiles_where_it_is_offered() {
    let all = cases();
    assert!(
        all.len() >= 900,
        "the grid collapsed to {} cases — the fixture is not being generated",
        all.len()
    );
    let mut broken: Vec<String> = Vec::new();
    for c in all.iter().filter(|c| c.legal) {
        if let Err(e) = compiles(&c.source) {
            let first = e.lines().next().unwrap_or("").to_string();
            broken.push(format!(
                "  {}/{}/{}  {first}\n     {}",
                c.ctx,
                c.lang,
                c.cmd,
                c.source.replace('\n', "⏎")
            ));
        }
    }
    assert!(
        broken.is_empty(),
        "{} of {} offered insertions do not compile:\n{}",
        broken.len(),
        all.len(),
        broken.join("\n"),
    );
}

/// Nothing the editor offers may land somewhere it does not belong.
///
/// Compiling is the low bar, and for the five structural children it was never
/// the bar at all: `#פריט` outside a list has always compiled, printed its
/// words, drawn no bullet and said nothing. The engine draws a badge on one now,
/// so "did this insertion make sense where it was offered" is a question the
/// grid can finally ask — of every command at every position, in both languages.
///
/// This is the half that proves the two sides agree. `legalAt` greys a control
/// from `STRUCTURAL_CHILDREN`, generated from the prelude's `_kd_parents`; the
/// badge is drawn by `_kd_items` reading that same dictionary. Nine hundred-odd
/// positions where the chrome and the engine have to reach the same verdict, and
/// before this there was no test that could have noticed them disagreeing.
#[test]
fn every_offered_insertion_lands_somewhere_it_belongs() {
    let mut wrong: Vec<String> = Vec::new();
    for c in cases().iter().filter(|c| c.legal) {
        if let Some(page) = page_text(&c.source) {
            if common::has_badge(&page) {
                wrong.push(format!(
                    "  {}/{}/{}  offered here, and the page says it does not belong\n     {}",
                    c.ctx,
                    c.lang,
                    c.cmd,
                    c.source.replace('\n', "⏎")
                ));
            }
        }
    }
    assert!(
        wrong.is_empty(),
        "{} offered insertions are badged on the page:\n{}",
        wrong.len(),
        wrong.join("\n"),
    );
}

/// A control the product greys out has to be genuinely unusable there.
///
/// A grey button is a promise that the thing would not have worked. If it would
/// have, the writer has been refused a legal operation and told nothing useful.
#[test]
fn every_refused_insertion_would_really_have_failed() {
    let mut wrong: Vec<String> = Vec::new();
    let mut refused = 0;
    for c in cases().iter().filter(|c| !c.legal) {
        refused += 1;
        let why = c.reason.as_deref().unwrap_or("(no reason)");
        if refusal_must_show_a_badge(c.reason.as_deref()) {
            // Compiles — and has to, or the refusal is being justified by the
            // wrong evidence — but reaches the page carrying the badge.
            match page_text(&c.source) {
                None => wrong.push(format!(
                    "  {}/{}/{}  refused as {why:?}, and does not compile at all",
                    c.ctx, c.lang, c.cmd
                )),
                Some(page) if !common::has_badge(&page) => wrong.push(format!(
                    "  {}/{}/{}  refused as {why:?}, but the page is clean",
                    c.ctx, c.lang, c.cmd
                )),
                Some(_) => {}
            }
        } else if compiles(&c.source).is_ok() {
            wrong.push(format!(
                "  {}/{}/{}  refused as {why:?}, but it compiles fine",
                c.ctx, c.lang, c.cmd
            ));
        }
    }
    assert!(
        refused > 0,
        "nothing is refused anywhere — is `legalAt` wired up?"
    );
    assert!(wrong.is_empty(), "over-refusal:\n{}", wrong.join("\n"));
}

// ---------------------------------------------------------------- both languages
//
// Both survivors of `registry.rs`, which is gone.
//
// `registry.rs` held `ONLY_AT_TOP`: nine commands exempted from its nesting
// sweep, each with a written reason, and `continue`d past. An entry there was
// **unfalsifiable by construction** — a listed command could never make the test
// red no matter what it did — and six of the nine were wrong. `תוכן`,
// `הערות_בסוף`, `הערות_בסוף_צד`, `הערות_מדורגות`, `מפתח_ענינים` and
// `מפתח_מקורות` are all `legal: true` in `note-body`, `list-in-item` and
// `table-in-cell` in this very fixture, and were being compiled there, and
// passing. So one test asserted they nest and another skipped them for not
// being able to, and both were green: two surfaces, one lying, nothing to catch
// it — reproduced inside the suite that exists to detect exactly that.
//
// The grid has no skip list. Where a command may go is stated once, by
// `mode.ts`'s `legalAt`, where the UI reads it, and it is checked in *both*
// directions above: a legal case must compile, and a refused case must really
// fail. A wrong exemption cannot hide in that, because there are no exemptions
// — only claims the compiler settles.
//
// **On widening this grid to English, which was tried the wrong way first.**
// The obvious version is to compile every case again with the command names
// swapped for their English pair. That was built, and it failed, and the
// failures were about the fixture rather than the product: the Insert menu, the
// toolbar and the palette all wrote `c.insert` **verbatim**, so the app never
// wrote an English registry name into anything. An English writer who picked
// Footnote got `#הערה[]` in their English document. A grid of English insertions
// therefore asserted a path no writer could reach, and its failures — a Hebrew
// parameter name left inside an English call — were artefacts of the swap.
//
// The comment that used to sit here named the alternative and stopped there:
// *"either the product change (translate the insertion by the document's
// language, the way `lists.ts`, `headings.ts`, `table.ts` and `note-commands.ts`
// already do) or nothing."* It was right, and for eleven months the answer was
// nothing — which is the shape the whole-repo report named: the diagnosis is
// correct, it is written down, and the sweep never runs.
//
// The product change landed. `mode.ts`'s `insertionAt` spells a snippet in the
// document's own language — **names and parameter names both**, through
// `COMMAND_EN` and `PARAM_EN`, which are generated from the prelude's `#let`
// lines and its `_en_params` and are what actually make the pairing. So the
// English half of this grid is now the same claim as the Hebrew half: this is
// what the product writes when a writer presses that button, here, and it
// compiles. Twelve positions × two languages × every command, and no case is
// reachable only by a test.
//
// The Hebrew half came out byte-identical to the day before, which is worth
// recording: the language axis is additive, and the 1,035 documents that caught
// 384 broken insertions still say exactly what they said.

/// Every registry name resolves to something in the prelude, in both languages.
///
/// Moved from `registry.rs`. A command offered by name that the compiler has
/// never heard of is the purest form of the product lying to the writer — and
/// unlike the sweeps above, this one covers the commands whose *body* cannot be
/// filled in usefully, so it stays as its own statement rather than being
/// implied by them.
#[test]
fn every_command_exists_in_both_languages() {
    let mut seen: Vec<(String, String)> = Vec::new();
    for c in cases() {
        if !seen.iter().any(|(h, _)| *h == c.cmd) {
            seen.push((c.cmd.clone(), c.en.clone()));
        }
    }
    assert!(
        seen.len() > 90,
        "the registry collapsed to {} commands",
        seen.len()
    );
    let mut missing = Vec::new();
    for (he, en) in &seen {
        for name in [he, en] {
            if compiles(&format!("#{{ let _ = {name} }}\n")).is_err() {
                missing.push(format!("{name} (from #{he})"));
            }
        }
    }
    assert!(
        missing.is_empty(),
        "{} registry name(s) do not exist in the prelude:\n{}",
        missing.len(),
        missing.join("\n"),
    );
}

/// A command given text puts that text on the page.
///
/// Moved from `registry.rs`, and the other half of "does it work": the sweeps
/// above prove a snippet *compiles*, and a command that compiles to nothing at
/// all is the failure the chooser and `coverage.test.mjs` exist against.
///
/// `RENDERS_ELSEWHERE` is a narrowing of one assertion rather than a skip list.
/// The difference is the whole reason `ONLY_AT_TOP` is gone: an entry here
/// excuses a command from *this* claim only, and every one of these commands is
/// still compiled in nine contexts, in two languages, above. An entry in
/// `ONLY_AT_TOP` removed a command from every assertion in its file.
///
/// Two very different things are in it, and the difference is worth writing out.
/// Most are correct by design: a marker prints nothing, a reference prints a
/// number rather than its own name, an index entry prints in the index, and
/// maths reaches the page as math italics rather than the ASCII that was typed.
/// The `מדור_*` bands and `הערתסיום` are correct only in the sense that a loaded
/// gun is correct — they collect their text and print nothing until a matching
/// dump call exists somewhere. The old file's comment ended "until that exists
/// this comment is the record that it is owed." It exists: `apparatus.ts` finds
/// them, `apparatus-lint.ts` offers the dump call, and `lints.test.mjs` holds it.
#[test]
fn a_command_given_text_shows_that_text() {
    const RENDERS_ELSEWHERE: &[(&str, &str)] = &[
        (
            "מדור_א",
            "collected; prints where #הערות_מדורגות() is called",
        ),
        (
            "מדור_ב",
            "collected; prints where #הערות_מדורגות() is called",
        ),
        (
            "מדור_ג",
            "collected; prints where #הערות_מדורגות() is called",
        ),
        (
            "מדור_בדרגה",
            "collected; prints where #הערות_מדורגות() is called",
        ),
        (
            "הערתסיום",
            "collected; prints where #הערות_בסוף() is called",
        ),
        (
            "גוף_הערה",
            "a deferred body: prints at its marker, not its definition",
        ),
        (
            "ערך",
            "an index entry: its text prints in the generated index",
        ),
        (
            "נוסחה",
            "maths: reaches the page as math italics, not as the ASCII typed",
        ),
        ("נוסחה_בשורה", "maths, inline: the same"),
        ("סימניה", "a marker: prints nothing by design"),
        ("הפניה", "a reference: prints a number, not its own name"),
        (
            "כלול",
            "includes another document; there is no other document here",
        ),
        (
            "הערת_עורך",
            "an editorial comment: renders in review mode and never prints",
        ),
    ];
    const MARK: &str = "טקסטמיוחד";

    let mut swallowed = Vec::new();
    let mut checked = 0;
    // The `prose` row is the plain case — one command in a paragraph, which is
    // where "did it print" has an unambiguous answer.
    for c in cases().iter().filter(|c| c.ctx == "prose" && c.legal) {
        if c.cmd.starts_with("הגדרות") || RENDERS_ELSEWHERE.iter().any(|(n, _)| *n == c.cmd) {
            continue;
        }
        // Only a snippet with an empty slot has somewhere to put the text.
        if !c.source.contains("[]") {
            continue;
        }
        let src = c.source.replacen("[]", &format!("[{MARK}]"), 1);
        let Ok(doc) = probe::layout(&src, &DocConfig::default()) else {
            continue; // owned by the compile sweep above
        };
        checked += 1;
        let page: String = probe::text_runs(&doc)
            .iter()
            .map(|r| r.text.as_str())
            .collect();
        if !page.contains(MARK) {
            swallowed.push(format!("#{} → {}", c.cmd, src.replace('\n', "⏎")));
        }
    }
    assert!(
        checked > 30,
        "only {checked} commands had a text slot — has the fixture changed shape?"
    );
    assert!(
        swallowed.is_empty(),
        "{} command(s) were given text and did not print it:\n{}",
        swallowed.len(),
        swallowed.join("\n"),
    );
}

/// No command is exempt from the grid, and the nine that used to be are in it.
///
/// This is the fence over the deletion. `ONLY_AT_TOP` listed nine commands that
/// `registry.rs` skipped, and six of them were being compiled in exactly the
/// contexts it claimed they could not appear in — by this file, passing, at the
/// same time. The way that comes back is not somebody re-adding the constant; it
/// is a `continue` inside one of the sweeps above, or a command quietly dropping
/// out of the fixture. So the shape of the grid is asserted rather than assumed:
/// every command × every context, no gaps, and a judgement recorded for each.
#[test]
fn the_grid_exempts_nothing() {
    let all = cases();
    let mut commands: Vec<&str> = all.iter().map(|c| c.cmd.as_str()).collect();
    commands.sort_unstable();
    commands.dedup();
    let mut contexts: Vec<&str> = all.iter().map(|c| c.ctx.as_str()).collect();
    contexts.sort_unstable();
    contexts.dedup();
    let mut langs: Vec<&str> = all.iter().map(|c| c.lang.as_str()).collect();
    langs.sort_unstable();
    langs.dedup();

    // The language axis is asserted rather than assumed, because the way it
    // goes is not somebody deleting it: it is one `CONTEXTS` entry gaining a
    // ninth position and no English twin, which halves the coverage of that
    // position and changes no total anybody looks at.
    assert_eq!(
        langs,
        ["en", "he"],
        "the grid is being asked in {langs:?} — a position with no English twin \
         is a position whose rule is fenced in one language only",
    );
    assert_eq!(
        all.len(),
        commands.len() * contexts.len() * langs.len(),
        "the grid has holes: {} commands × {} contexts × {} languages should be {} cases, not {}",
        commands.len(),
        contexts.len(),
        langs.len(),
        commands.len() * contexts.len() * langs.len(),
        all.len(),
    );

    // The nine, by name. Six of them were exempted from nesting while being
    // compiled nested here; two are genuinely top-level and the grid says so
    // itself, by refusing them — which is a claim `every_refused_insertion`
    // above then has to make good on against the compiler.
    const FORMERLY_EXEMPT: &[&str] = &[
        "מקטע_עמוד",
        "מעבר_עמוד",
        "תוכן",
        "הערות_בסוף",
        "הערות_בסוף_צד",
        "הערות_מדורגות",
        "מפתח_ענינים",
        "מפתח_מקורות",
    ];
    for name in FORMERLY_EXEMPT {
        let rows: Vec<&Case> = all.iter().filter(|c| c.cmd == *name).collect();
        assert_eq!(
            rows.len(),
            contexts.len() * langs.len(),
            "#{name} is missing from {} of the {} context/language pairs — it is being skipped again",
            contexts.len() * langs.len() - rows.len(),
            contexts.len() * langs.len(),
        );
        // And every refusal carries a reason. An exemption with no reason is how
        // the old list started.
        for r in rows.iter().filter(|r| !r.legal) {
            assert!(
                r.reason.as_deref().is_some_and(|s| s.len() > 3),
                "#{name} is refused in {}/{} with no reason given",
                r.ctx,
                r.lang
            );
        }
    }
}
