//! Every command, at every kind of caret position, compiled.
//!
//! `registry.rs` compiles each snippet standalone and in three fixed nestings.
//! That is not where the writer is. The writer is *between two list items*, and
//! there the editor wrote markup that would not compile — for every command in
//! the registry, without exception, in three separate positions. 384 of 1,026
//! documents failed the first time this grid was swept, and every test in the
//! suite was green.
//!
//! The fixture is generated by `app/tools/emit-insertion-fixtures.mjs`, which
//! runs the app's own insertion path (`insertionAt`) — not a re-implementation
//! of it — and `npm test` checks it for staleness so the two sides cannot drift.
//!
//! Two assertions, and the second is the one that keeps the first honest:
//!
//!   1. everything the product offers here must compile
//!   2. everything the product greys out here must genuinely fail
//!
//! Without (2) the cheapest way to green is to grey the whole toolbar.

use ksav_engine::probe;
use ksav_engine::DocConfig;

const FIXTURE: &str = include_str!("fixtures/insertions.json");

struct Case {
    ctx: String,
    cmd: String,
    legal: bool,
    reason: Option<String>,
    source: String,
}

fn cases() -> Vec<Case> {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    v["cases"]
        .as_array()
        .expect("cases array")
        .iter()
        .map(|c| Case {
            ctx: c["ctx"].as_str().unwrap().to_string(),
            cmd: c["cmd"].as_str().unwrap().to_string(),
            legal: c["legal"].as_bool().unwrap(),
            reason: c["reason"].as_str().map(str::to_string),
            source: c["source"].as_str().unwrap().to_string(),
        })
        .collect()
}

fn compiles(source: &str) -> Result<(), String> {
    match probe::layout(source, &DocConfig::default()) {
        Ok(_) => Ok(()),
        Err(d) => Err(format!("{d:?}")),
    }
}

/// Nothing the editor offers may produce markup that will not compile.
#[test]
fn every_offered_insertion_compiles_where_it_is_offered() {
    let all = cases();
    assert!(
        all.len() >= 900,
        "the grid collapsed to {} cases — the fixture is not being generated",
        all.len()
    );
    let mut broken: Vec<String> = Vec::new();
    for c in all.iter().filter(|c| c.legal) {
        if let Err(e) = compiles(&c.source) {
            let first = e.lines().next().unwrap_or("").to_string();
            broken.push(format!(
                "  {}/{}  {first}\n     {}",
                c.ctx,
                c.cmd,
                c.source.replace('\n', "⏎")
            ));
        }
    }
    assert!(
        broken.is_empty(),
        "{} of {} offered insertions do not compile:\n{}",
        broken.len(),
        all.len(),
        broken.join("\n"),
    );
}

/// A control the product greys out has to be genuinely unusable there.
///
/// A grey button is a promise that the thing would not have worked. If it would
/// have, the writer has been refused a legal operation and told nothing useful.
#[test]
fn every_refused_insertion_would_really_have_failed() {
    let mut wrong: Vec<String> = Vec::new();
    let mut refused = 0;
    for c in cases().iter().filter(|c| !c.legal) {
        refused += 1;
        if compiles(&c.source).is_ok() {
            wrong.push(format!(
                "  {}/{}  refused as {:?}, but it compiles fine",
                c.ctx,
                c.cmd,
                c.reason.as_deref().unwrap_or("(no reason)")
            ));
        }
    }
    assert!(
        refused > 0,
        "nothing is refused anywhere — is `legalAt` wired up?"
    );
    assert!(wrong.is_empty(), "over-refusal:\n{}", wrong.join("\n"));
}
