//! Every note layout, at every kind of caret position, compiled.
//!
//! The sibling of `insertion.rs`, and it exists because that grid could not see
//! this path. `insert.rs`'s `plan` answers a note *before* `legalAt` and before
//! `insertionAt` — correctly, because a note is a layout and not a string, and
//! with deferred bodies its prose does not go in at the caret at all — so the
//! one insertion in the product with the most moving parts was the one outside
//! every check that had ever been written for insertions.
//!
//! Swept for the first time: **288 of 1,248 documents would not compile.** One
//! engine message between them, *the character `#` is not valid in code*, and a
//! distribution that is the whole diagnosis:
//!
//! ```text
//! list-after-open       96/96 fail
//! list-between-items    96/96 fail
//! table-between-cells   96/96 fail
//! the other ten          0/96
//! ```
//!
//! Not 288 bugs — one. Every note, in every code-mode position: the same three
//! positions that broke all 114 registry commands the first time anybody swept
//! for this, found again in the single path exempted from the fix. The whole
//! suite was green throughout, here and in `app/test`, because nothing asked.
//!
//! The fixture is generated by `app/tools/emit-note-insertion-fixtures.mjs`,
//! which runs the app's own `notes.applyChoice` — not a re-implementation of it
//! — and `npm test` checks it for staleness so the two sides cannot drift.
//!
//! One assertion, and unlike `insertion.rs` there is deliberately no second
//! half about refusals: the note chooser refuses nothing here. Every layout it
//! offers is offered at every position, so "everything offered compiles" is the
//! entire claim, and greying something would be a change to the product rather
//! than a way to make this green.

use ksav_engine::probe;
use ksav_engine::DocConfig;

const FIXTURE: &str = include_str!("fixtures/note-insertions.json");

struct Case {
    ctx: String,
    lang: String,
    choice: String,
    id: String,
    layer: u64,
    deferred: bool,
    source: String,
}

fn cases() -> Vec<Case> {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    v["cases"]
        .as_array()
        .expect("cases array")
        .iter()
        .map(|c| Case {
            ctx: c["ctx"].as_str().unwrap().to_string(),
            lang: c["lang"].as_str().unwrap().to_string(),
            choice: c["choice"].as_str().unwrap().to_string(),
            id: c["id"].as_str().unwrap().to_string(),
            layer: c["layer"].as_u64().unwrap(),
            deferred: c["deferred"].as_bool().unwrap(),
            source: c["source"].as_str().unwrap().to_string(),
        })
        .collect()
}

/// Nothing the notes chooser offers may produce markup that will not compile.
#[test]
fn every_note_insertion_compiles_where_it_is_offered() {
    let all = cases();
    // The grid asserted before anything is concluded from it. A fixture that
    // silently emptied would turn this whole file into a loop over nothing,
    // which is the cheapest possible green and the exact failure this test was
    // written to end.
    assert!(
        all.len() >= 1000,
        "the grid collapsed to {} cases — the fixture is not being generated",
        all.len()
    );
    // Both halves of the deferred axis are really present. Deferred rewrites the
    // snippet into a marker/body pair and files the body elsewhere in the
    // document; it is not the inline case with an extra line, and a fixture that
    // had quietly stopped emitting it would take half the coverage with it.
    assert!(
        all.iter().any(|c| c.deferred) && all.iter().any(|c| !c.deferred),
        "the grid must carry both inline and deferred note bodies"
    );
    // And so are the code-mode positions, which are the only ones that ever
    // failed. Named rather than counted: if the context table in the emitter
    // loses one of these three, every assertion below still passes and the fence
    // is gone.
    for ctx in ["list-after-open", "list-between-items", "table-between-cells"] {
        assert!(
            all.iter().any(|c| c.ctx == ctx),
            "the grid must carry the {ctx} position — it is where all 288 failures were"
        );
    }

    let mut broken: Vec<String> = Vec::new();
    for c in &all {
        if let Err(d) = probe::layout(&c.source, &DocConfig::default()) {
            let first = d
                .first()
                .map(|x| x.raw.lines().next().unwrap_or("").to_string())
                .unwrap_or_default();
            broken.push(format!(
                "  {}/{}/{} layer {} {}  {first}\n     {}",
                c.ctx,
                c.lang,
                c.choice,
                c.layer,
                if c.deferred { "deferred" } else { "inline" },
                c.source.replace('\n', "⏎")
            ));
        }
    }
    assert!(
        broken.is_empty(),
        "{} of {} note insertions do not compile:\n{}",
        broken.len(),
        all.len(),
        broken
            .iter()
            .take(20)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// Every layout the chooser publishes reaches the grid.
///
/// Separate from the sweep above, and it is the assertion that keeps the sweep
/// honest as the product grows: a twelfth note layout added to `NOTE_CHOICES`
/// is covered by the emitter for free, but a layout *removed* from the emitter's
/// loop — or one whose `markersOf` stops reporting its tiers — would shrink the
/// grid silently while every other assertion here stayed green.
#[test]
fn the_grid_covers_every_layout_and_both_body_placements() {
    let all = cases();
    let ids: std::collections::BTreeSet<&str> = all.iter().map(|c| c.id.as_str()).collect();
    assert!(
        ids.len() >= 11,
        "the chooser publishes eleven layouts; the grid covers {}: {:?}",
        ids.len(),
        ids
    );
    // Both languages, for the reason `insertion.rs` learned the hard way: the
    // best fence in this repository once asked all 1,035 of its questions in
    // Hebrew, and a note marker arriving in Hebrew inside an English document is
    // exactly the class that hid there.
    for lang in ["he", "en"] {
        assert!(
            all.iter().any(|c| c.lang == lang),
            "the grid must ask its questions in {lang} too"
        );
    }
    // A tiered layout contributes more than one layer, or `markersOf` has
    // stopped reporting tiers and two thirds of the tiered cards are untested.
    assert!(
        all.iter().any(|c| c.layer > 0),
        "no case carries a tier above the first — the tiered layouts are not being swept"
    );
}
