//! The editor's scanner, contradicted by Typst's own parser.
//!
//! # The finding this answers
//!
//! `app/src/spans.ts` decides, for every character of the document, whether it
//! is prose or code. Everything downstream hangs off that answer: whether `"`
//! is a gershayim or opens a string literal, where an argument list ends, which
//! text the spell checker sees, and — through the speculative heal — what gets
//! written into the writer's file when a bracket looks unbalanced.
//!
//! It got that answer wrong for a bare `(`. In markup, `(` is a character;
//! the scanner opened *code*, so `(רש"י)` put the gershayim into a string, the
//! commas after it stopped separating arguments, and a list item silently
//! merged with the next one. The commonest construction in the language.
//!
//! Fourteen unit tests of the scanner were green throughout, and they were
//! always going to be: each one was written by somebody who already held the
//! wrong rule, so each one asserted it. **No amount of that class of test finds
//! this class of bug.** The only thing that does is an authority which was not
//! consulted when the rule was written.
//!
//! # Why an oracle is possible at all
//!
//! The README said the editor "cannot ask the engine, because the answer has to
//! be synchronous, pure and available mid-keystroke". That is true of the
//! **compiler** — 14–30 ms for one page, 5.6 s at 170, and wasm-bindgen cannot
//! yield mid-compile — and it is false of the **parser**. `Source::detached`
//! parses with no world, no fonts, no assets and no layout.
//!
//! So the scanner stays exactly as it is at runtime, and here, offline, over
//! every document in the repository, it is checked against `typst::syntax`.
//!
//! # What is compared
//!
//! Four claims where both sides say the same thing and any disagreement is a
//! bug. `src/parse.rs` explains why a per-offset comparison is *not* one of
//! them — `#הדגשה[…]` puts `הדגשה` in a Typst `Ident` under code and the
//! scanner keeps it in content, and both are right about their own job.
//!
//!   1. **Text is prose.** Every character Typst lexed as markup `Text`, the
//!      scanner must call content. This is the `(` bug's exact signature.
//!   2. **Strings, both directions.** A `Str` node is a string literal and
//!      nothing else is. The reverse direction — the scanner claiming a string
//!      Typst does not have — is the one the bug tripped.
//!   3. **Comments, both directions**, exactly.
//!   4. **Content blocks.** Every `[…]` Typst calls a `ContentBlock` must be a
//!      group the scanner found. Not the converse: a bare `[` in prose is
//!      literal `Text` to Typst and a harmless content group to the scanner.
//!
//! The corpus is generated by `app/tools/emit-scan-oracle.mjs`: the ten
//! templates, both starter documents, the Girsa buffer, every note layout and
//! structural edit the app produces, and the whole insertion grid — every
//! command the UI offers spliced into every kind of caret position. Twelve
//! hundred documents, and the point of the grid is that nobody chose them.

use ksav_engine::parse::{self, Mode};
use typst::syntax::SyntaxKind;

const FIXTURE: &str = include_str!("fixtures/scan-oracle.json");

/// One document, and everything `spans.ts` believes about it.
struct Doc {
    id: String,
    text: String,
    /// UTF-16 ranges the scanner calls code.
    code: Vec<(usize, usize)>,
    /// String-literal contents, without the quotes.
    strings: Vec<(usize, usize)>,
    comments: Vec<(usize, usize)>,
    /// `[…]` groups, contents only.
    groups: Vec<(usize, usize)>,
}

fn ranges(v: &serde_json::Value, key: &str) -> Vec<(usize, usize)> {
    v[key]
        .as_array()
        .unwrap_or_else(|| panic!("`{key}` is an array"))
        .iter()
        .map(|r| {
            (
                r[0].as_u64().expect("a number") as usize,
                r[1].as_u64().expect("a number") as usize,
            )
        })
        .collect()
}

fn docs() -> Vec<Doc> {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("the fixture parses");
    v["docs"]
        .as_array()
        .expect("docs array")
        .iter()
        .map(|d| Doc {
            id: d["id"].as_str().expect("an id").to_string(),
            text: d["text"].as_str().expect("a text").to_string(),
            code: ranges(d, "code"),
            strings: ranges(d, "strings"),
            comments: ranges(d, "comments"),
            groups: ranges(d, "groups"),
        })
        .collect()
}

/// Byte offset for each UTF-16 unit, plus one past the end.
///
/// The scanner's offsets are JavaScript string indices, which are UTF-16 code
/// units; Typst's are bytes. Converting once per document is the whole of the
/// impedance mismatch, and doing it explicitly is better than the two sides
/// agreeing by accident because the corpus happens to be all-BMP.
fn utf16_to_byte(text: &str) -> Vec<usize> {
    let mut map = Vec::with_capacity(text.len() + 1);
    for (byte, ch) in text.char_indices() {
        for _ in 0..ch.len_utf16() {
            map.push(byte);
        }
    }
    map.push(text.len());
    map
}

/// The byte ranges of `spans`, given a UTF-16 map.
fn to_bytes(map: &[usize], spans: &[(usize, usize)]) -> Vec<(usize, usize)> {
    spans
        .iter()
        .map(|&(a, b)| (map[a.min(map.len() - 1)], map[b.min(map.len() - 1)]))
        .collect()
}

fn covered(ranges: &[(usize, usize)], from: usize, to: usize) -> bool {
    ranges.iter().any(|&(a, b)| a < to && from < b)
}

/// A snippet of `text` around `[from, to)`, for a failure message somebody has
/// to read at two in the morning.
fn around(text: &str, from: usize, to: usize) -> String {
    let lo = text[..from]
        .char_indices()
        .rev()
        .nth(30)
        .map_or(0, |(i, _)| i);
    let hi = text[to..]
        .char_indices()
        .nth(30)
        .map_or(text.len(), |(i, _)| to + i);
    format!(
        "…{}«{}»{}…",
        &text[lo..from],
        &text[from..to],
        &text[to..hi]
    )
}

/// Documents Typst could not parse cleanly are not an oracle for anything.
///
/// Reported rather than silently dropped: a sweep that quietly stops covering
/// its corpus reads exactly like a sweep that passes.
fn parses_cleanly(p: &parse::Partition) -> bool {
    !p.leaves.iter().any(|l| l.kind == SyntaxKind::Error)
}

struct Sweep {
    checked: usize,
    skipped: Vec<String>,
    wrong: Vec<String>,
}

fn sweep(mut check: impl FnMut(&Doc, &parse::Partition, &[usize], &mut Vec<String>)) -> Sweep {
    let mut out = Sweep {
        checked: 0,
        skipped: vec![],
        wrong: vec![],
    };
    for d in docs() {
        let p = parse::partition(&d.text);
        if !parses_cleanly(&p) {
            out.skipped.push(d.id.clone());
            continue;
        }
        out.checked += 1;
        let map = utf16_to_byte(&d.text);
        let mut wrong = vec![];
        check(&d, &p, &map, &mut wrong);
        for w in wrong {
            out.wrong.push(format!("{}: {w}", d.id));
        }
    }
    out
}

impl Sweep {
    fn assert_clean(&self, what: &str) {
        assert!(
            self.checked > 1_000,
            "the {what} sweep only reached {} documents — the corpus has stopped arriving",
            self.checked
        );
        assert!(
            self.wrong.is_empty(),
            "{} of {} documents disagree about {what}:\n{}",
            self.wrong.len(),
            self.checked,
            self.wrong
                .iter()
                .take(20)
                .cloned()
                .collect::<Vec<_>>()
                .join("\n"),
        );
    }
}

#[test]
fn every_character_typst_lexed_as_prose_is_prose_to_the_scanner() {
    // The `(` bug, stated as a property. `(רש"י)` in a body is markup `Text`
    // to Typst from end to end; the scanner called everything after the paren
    // code, and the gershayim opened a string that ate the rest of the group.
    let s = sweep(|d, p, map, wrong| {
        let code = to_bytes(map, &d.code);
        for leaf in p.of_kind(SyntaxKind::Text) {
            if leaf.mode != Mode::Content || p.touches_math(leaf.from, leaf.to) {
                continue;
            }
            if covered(&code, leaf.from, leaf.to) {
                wrong.push(format!(
                    "the scanner calls this code, Typst calls it text: {}",
                    around(&d.text, leaf.from, leaf.to)
                ));
            }
        }
    });
    s.assert_clean("prose");
}

#[test]
fn a_string_literal_is_one_to_both_of_them() {
    // Both directions, and the second is the one that fired: the scanner
    // reporting a string that Typst does not have is how a gershayim swallows
    // a document.
    let s = sweep(|d, p, map, wrong| {
        let mut typst: Vec<(usize, usize)> = p
            .of_kind(SyntaxKind::Str)
            .filter(|l| l.mode == Mode::Code)
            // A `Str` node is `"…"`; the scanner records the contents.
            .map(|l| (l.from + 1, l.to - 1))
            .collect();
        let mut theirs = to_bytes(map, &d.strings);
        typst.retain(|&(a, b)| !p.touches_math(a, b));
        theirs.retain(|&(a, b)| !p.touches_math(a, b));
        typst.sort_unstable();
        theirs.sort_unstable();
        for &(a, b) in &theirs {
            if !typst.contains(&(a, b)) {
                wrong.push(format!(
                    "the scanner sees a string Typst does not: {}",
                    around(&d.text, a, b)
                ));
            }
        }
        for &(a, b) in &typst {
            if !theirs.contains(&(a, b)) {
                wrong.push(format!(
                    "Typst sees a string the scanner does not: {}",
                    around(&d.text, a, b)
                ));
            }
        }
    });
    s.assert_clean("string literals");
}

#[test]
fn a_comment_is_one_to_both_of_them() {
    // `#הדגשה[אלף // בית]` does not compile, because the `//` eats the closing
    // bracket — so a scanner that treated `//` inside a body as prose would
    // call that document balanced while the compiler did not.
    let s = sweep(|d, p, map, wrong| {
        let mut typst: Vec<(usize, usize)> = p.comments().map(|l| (l.from, l.to)).collect();
        let mut theirs = to_bytes(map, &d.comments);
        typst.retain(|&(a, b)| !p.touches_math(a, b));
        theirs.retain(|&(a, b)| !p.touches_math(a, b));
        typst.sort_unstable();
        theirs.sort_unstable();
        if typst != theirs {
            wrong.push(format!(
                "comments differ — Typst {:?}, the scanner {:?}",
                typst
                    .iter()
                    .map(|&(a, b)| &d.text[a..b])
                    .collect::<Vec<_>>(),
                theirs
                    .iter()
                    .map(|&(a, b)| &d.text[a..b])
                    .collect::<Vec<_>>(),
            ));
        }
    });
    s.assert_clean("comments");
}

#[test]
fn every_content_block_typst_found_is_a_group_the_scanner_found() {
    // One direction only, deliberately: a bare `[` in prose is `Text` to Typst
    // and a content group to the scanner, and both are content, so the converse
    // would fail on documents that are entirely correct.
    let s = sweep(|d, p, map, wrong| {
        let theirs = to_bytes(map, &d.groups);
        for b in &p.content_blocks {
            if p.touches_math(b.from, b.to) {
                continue;
            }
            if !theirs.contains(&(b.from, b.to)) {
                wrong.push(format!(
                    "Typst has a content block the scanner missed: {}",
                    around(&d.text, b.from, b.to)
                ));
            }
        }
    });
    s.assert_clean("content blocks");
}

#[test]
fn the_corpus_is_the_whole_corpus() {
    // The number that stops this becoming a sweep of nothing. It is the count
    // the generator produced, and it moves when a template, a note layout, a
    // structural edit or a command is added — all four of which should move it.
    let all = docs();
    assert!(
        all.len() > 1_200,
        "the corpus is {} documents; it was 1,221",
        all.len()
    );
    for prefix in [
        "regression:",
        "template:",
        "starter:",
        "fixture:",
        "insertion:",
        "note-layouts:",
        "structure-edits:",
    ] {
        assert!(
            all.iter().any(|d| d.id.starts_with(prefix)),
            "nothing in the corpus comes from `{prefix}` any more"
        );
    }
    // And every one of them is a document, not an empty string somebody's
    // `?? \"\"` produced.
    for d in &all {
        assert!(!d.text.trim().is_empty(), "{} is empty", d.id);
    }
}

#[test]
fn what_typst_cannot_parse_is_named_rather_than_dropped() {
    // A skipped document is fine — `insertion.rs` already asserts *why* the
    // illegal cases are illegal — but a growing skip list is a sweep quietly
    // going hollow, and the only way to notice is to print it.
    let s = sweep(|_, _, _, _| {});
    assert!(
        s.skipped.len() * 20 < s.checked,
        "{} of {} documents no longer parse; Typst cannot be an oracle for them:\n{}",
        s.skipped.len(),
        s.checked + s.skipped.len(),
        s.skipped.join("\n"),
    );
}
