//! Does the editor's structural editing produce source that compiles?
//!
//! The list operations arrived with 65 green unit tests. One of them checked
//! that brackets balanced and that no `#` sat inside an argument list — and
//! "outdent" passed it while emitting `],,` and an item with no separator
//! before it. Balanced brackets are not legal Typst. A pure-function test
//! cannot know the difference; the compiler is the only authority.
//!
//! So every structural edit the UI can perform is rendered here. The fixture is
//! generated by `app/tools/emit-structure-fixtures.mjs`, which `npm test` also
//! checks for staleness.
//!
//! A failure here is not a test problem. It means a button in the editor puts
//! the writer's document into a state where the preview goes blank.

use ksav_engine::probe;
use ksav_engine::DocConfig;

const FIXTURE: &str = include_str!("fixtures/structure-edits.json");

#[test]
fn every_structural_edit_still_compiles() {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    let cases = v["cases"].as_array().expect("cases array");
    assert!(cases.len() >= 30, "the fixture stopped covering the edits");

    let mut broken: Vec<String> = Vec::new();
    for c in cases {
        let name = c["name"].as_str().unwrap();
        let source = c["source"].as_str().unwrap();
        if let Err(diags) = probe::layout(source, &DocConfig::default()) {
            broken.push(format!("{name}:\n{source}\n  → {diags:?}"));
        }
    }
    assert!(
        broken.is_empty(),
        "{} structural edit(s) produce source that will not compile:\n\n{}",
        broken.len(),
        broken.join("\n\n"),
    );
}

/// An edit keeps the writer's words.
///
/// Losing text is worse than not compiling, because it is silent: the page
/// still renders and a sentence is simply gone. Delete is the one operation
/// allowed to remove something, and it is named so it can be excluded.
#[test]
fn no_structural_edit_silently_loses_text() {
    let v: serde_json::Value = serde_json::from_str(FIXTURE).expect("fixture parses");
    for c in v["cases"].as_array().unwrap() {
        let name = c["name"].as_str().unwrap();
        if name.contains("delete") {
            continue;
        }
        let source = c["source"].as_str().unwrap();
        let Ok(doc) = probe::layout(source, &DocConfig::default()) else {
            continue; // the compile test above owns this failure
        };
        let runs = probe::text_runs(&doc);
        let page: String = runs.iter().map(|r| r.text.as_str()).collect();
        // The words this document was built from, stated by the generator.
        // They used to be inferred from the case name, which meant a new family
        // of fixtures quietly checked the wrong words until the mismatch
        // surfaced as a confusing failure — three separate times. The side that
        // knows should be the side that says.
        let words: Vec<&str> = c["words"]
            .as_array()
            .expect("every case carries its words")
            .iter()
            .map(|w| w.as_str().unwrap())
            .collect();
        for w in &words {
            // Split cuts one word in half on purpose, so its first character
            // surviving is all that can be asked. Sliced by characters, not
            // bytes — `&w[..w.len()/2]` panics in the middle of a Hebrew letter,
            // which is the one bug this codebase should never ship twice.
            if name.contains("split") {
                let head: String = w.chars().take(1).collect();
                if page.contains(&head) {
                    continue;
                }
            }
            assert!(
                page.contains(w),
                "{name}: {w:?} is not on the page any more\n{source}",
            );
        }
    }
}
